// Code generated by gentable from Excel. DO NOT EDIT.
// server 端产物: 仅包含导出标记为 cs/s 的字段。

package server

import (
	"encoding/json"
	"fmt"
)

// ItemQuality 枚举，定义于 common.xlsx[EnumItemQuality]
type ItemQuality int32

const (
	ItemQualityWhite  ItemQuality = 1 // 普通(白)
	ItemQualityGreen  ItemQuality = 2 // 优秀(绿)
	ItemQualityBlue   ItemQuality = 3 // 精良(蓝)
	ItemQualityPurple ItemQuality = 4 // 史诗(紫)
	ItemQualityOrange ItemQuality = 5 // 传说(橙)
)

var itemQualityNames = map[ItemQuality]string{
	ItemQualityWhite:  "White",
	ItemQualityGreen:  "Green",
	ItemQualityBlue:   "Blue",
	ItemQualityPurple: "Purple",
	ItemQualityOrange: "Orange",
}

var itemQualityValues = map[string]ItemQuality{
	"White":  ItemQualityWhite,
	"Green":  ItemQualityGreen,
	"Blue":   ItemQualityBlue,
	"Purple": ItemQualityPurple,
	"Orange": ItemQualityOrange,
}

func (e ItemQuality) String() string {
	if s, ok := itemQualityNames[e]; ok {
		return s
	}
	return fmt.Sprintf("ItemQuality(%d)", int32(e))
}

// MarshalJSON 序列化为枚举名，保证 JSON 可读、可 diff
func (e ItemQuality) MarshalJSON() ([]byte, error) {
	if s, ok := itemQualityNames[e]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(int32(e))
}

// UnmarshalJSON 兼容枚举名("White")与数值(1)两种写法
func (e *ItemQuality) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err == nil {
		v, ok := itemQualityValues[s]
		if !ok {
			return fmt.Errorf("未知的 ItemQuality 枚举值: %q", s)
		}
		*e = v
		return nil
	}
	var i int64
	if err := json.Unmarshal(b, &i); err != nil {
		return fmt.Errorf("无法解析 ItemQuality: %w", err)
	}
	*e = ItemQuality(i)
	return nil
}
