// Code generated by gentable from Excel. DO NOT EDIT.
// server 端产物: 仅包含导出标记为 cs/s 的字段。

package server

// Drop 内联结构体，定义于 common.xlsx[StructDrop]
// 单元格写法: item:目标主键;rate:0.5;count:100;weight:100
type Drop struct {
	// 掉落道具ID
	Item int32 `json:"item"`
	// 掉落概率(0~1)
	Rate float64 `json:"rate"`
	// 掉落数量
	Count int32 `json:"count"`
	// 权重(可选,省略时取默认值1)
	Weight int32 `json:"weight"`
}

// Pos 内联结构体，定义于 common.xlsx[StructPos]
// 单元格写法: x:100;y:100
type Pos struct {
	// X坐标
	X int32 `json:"x"`
	// Y坐标
	Y int32 `json:"y"`
}
