package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// sides 两个导出端。client 包含 c+cs 字段，server 包含 s+cs 字段。
var sides = []string{"client", "server"}

// includeField 判断字段是否属于该端
func includeField(f *Field, side string) bool {
	switch side {
	case "client":
		return f.Flag == "cs" || f.Flag == "c"
	case "server":
		return f.Flag == "cs" || f.Flag == "s"
	}
	return false
}

// fieldsFor 返回某端实际导出的字段（主键必须为 cs，故首元素恒为主键）
func fieldsFor(t *Table, side string) []*Field {
	out := make([]*Field, 0, len(t.Fields))
	for _, f := range t.Fields {
		if includeField(f, side) {
			out = append(out, f)
		}
	}
	return out
}

func genHeader(pkg, note string) string {
	return fmt.Sprintf("// Code generated by gentable from Excel. DO NOT EDIT.\n// %s\n\npackage %s\n\n", note, pkg)
}

// WriteGoCode 为每个端生成一套独立代码:
//
//	<codeRoot>/client/  package client（仅 c+cs 字段）
//	<codeRoot>/server/  package server（仅 s+cs 字段）
//
// 每套包含: enum_gen.go / struct_gen.go / tables_gen.go / config_gen.go
func WriteGoCode(tables []*Table, enums []*EnumDef, structs []*StructDef, codeRoot string) error {
	refPK := func(sheet string) string {
		for _, t := range tables {
			if t.Sheet == sheet {
				return t.PKGoType()
			}
		}
		return "int32"
	}
	for _, side := range sides {
		dir := filepath.Join(codeRoot, side)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		note := fmt.Sprintf("%s 端产物: 仅包含导出标记为 cs/%s 的字段。", side, sideFlag(side))
		write := func(name, content string) error {
			// 生成代码统一 gofmt，保证与磁盘基线可稳定对比（diff 摘要不误报）
			formatted, err := format.Source([]byte(content))
			if err != nil {
				return fmt.Errorf("生成的 %s 不是合法 Go 代码: %w", name, err)
			}
			return os.WriteFile(filepath.Join(dir, name), formatted, 0o644)
		}
		if err := write("enum_gen.go", genEnums(enums, side, note)); err != nil {
			return err
		}
		if err := write("struct_gen.go", genStructs(structs, refPK, side, note)); err != nil {
			return err
		}
		if err := write("tables_gen.go", genTables(tables, refPK, side, note)); err != nil {
			return err
		}
		if err := write("config_gen.go", genConfig(tables, side, note)); err != nil {
			return err
		}
		if len(tables) > 0 {
			if err := write("embed_gen.go", genEmbed(side, note)); err != nil {
				return err
			}
		}
	}
	return nil
}

func sideFlag(side string) string {
	if side == "client" {
		return "c"
	}
	return "s"
}

// ------------------------------------------------------------ enum_gen.go

const enumUnmarshalTmpl = `
// UnmarshalJSON 兼容枚举名("White")与数值(1)两种写法
func (e *$T) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err == nil {
		v, ok := $values[s]
		if !ok {
			return fmt.Errorf("未知的 $T 枚举值: %q", s)
		}
		*e = v
		return nil
	}
	var i int64
	if err := json.Unmarshal(b, &i); err != nil {
		return fmt.Errorf("无法解析 $T: %w", err)
	}
	*e = $T(i)
	return nil
}
`

// genEnums 枚举两端各生成一份（类型系统一致，避免跨包依赖）
func genEnums(enums []*EnumDef, side, note string) string {
	buf := bytes.Buffer{}
	buf.WriteString(genHeader(side, note))
	if len(enums) == 0 {
		return buf.String()
	}
	buf.WriteString("import (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n")
	for _, e := range enums {
		lower := lowerFirst(e.Name)
		fmt.Fprintf(&buf, "\n// %s 枚举，定义于 %s[%s]\n", e.Name, e.File, e.Sheet)
		fmt.Fprintf(&buf, "type %s int32\n\nconst (\n", e.Name)
		for _, it := range e.Entries {
			comment := ""
			if it.Comment != "" {
				comment = " // " + it.Comment
			}
			fmt.Fprintf(&buf, "\t%s%s %s = %d%s\n", e.Name, it.Name, e.Name, it.Value, comment)
		}
		buf.WriteString(")\n\n")

		fmt.Fprintf(&buf, "var %sNames = map[%s]string{\n", lower, e.Name)
		for _, it := range e.Entries {
			fmt.Fprintf(&buf, "\t%s%s: %q,\n", e.Name, it.Name, it.Name)
		}
		fmt.Fprintf(&buf, "}\n\nvar %sValues = map[string]%s{\n", lower, e.Name)
		for _, it := range e.Entries {
			fmt.Fprintf(&buf, "\t%q: %s%s,\n", it.Name, e.Name, it.Name)
		}
		buf.WriteString("}\n")

		fmt.Fprintf(&buf, `
func (e %s) String() string {
	if s, ok := %sNames[e]; ok {
		return s
	}
	return fmt.Sprintf("%s(%%d)", int32(e))
}

// MarshalJSON 序列化为枚举名，保证 JSON 可读、可 diff
func (e %s) MarshalJSON() ([]byte, error) {
	if s, ok := %sNames[e]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(int32(e))
}
`, e.Name, lower, e.Name, e.Name, lower)

		r := strings.NewReplacer("$T", e.Name, "$values", lower+"Values")
		buf.WriteString(r.Replace(enumUnmarshalTmpl))
	}
	return buf.String()
}

// ------------------------------------------------------------ struct_gen.go

// genStructs 结构体两端各生成一份（同枚举，避免跨包依赖）
func genStructs(structs []*StructDef, refPK func(string) string, side, note string) string {
	buf := bytes.Buffer{}
	buf.WriteString(genHeader(side, note))
	if len(structs) == 0 {
		return buf.String()
	}
	for _, s := range structs {
		fmt.Fprintf(&buf, "\n// %s 内联结构体，定义于 %s[%s]\n// 单元格写法: %s\n",
			s.Name, s.File, s.Sheet, structCellExample(s))
		fmt.Fprintf(&buf, "type %s struct {\n", s.Name)
		for _, f := range s.Fields {
			if f.Comment != "" {
				fmt.Fprintf(&buf, "\t// %s\n", f.Comment)
			}
			fmt.Fprintf(&buf, "\t%s %s `json:%q`\n", f.GoName, f.Type.GoType(refPK), f.Name)
		}
		buf.WriteString("}\n")
	}
	return buf.String()
}

// structCellExample 生成填写示例，如 "item:1001;rate:0.5"
func structCellExample(s *StructDef) string {
	parts := make([]string, 0, len(s.Fields))
	for _, f := range s.Fields {
		parts = append(parts, f.Name+":"+typeExample(f.Type))
	}
	return strings.Join(parts, ";")
}

func typeExample(te *TypeExpr) string {
	switch te.Kind {
	case KInt, KInt64:
		return "100"
	case KFloat:
		return "0.5"
	case KBool:
		return "1"
	case KString:
		return "文本"
	case KEnum:
		return "枚举名"
	case KRef:
		return "目标主键"
	case KStruct:
		return "..."
	case KList:
		return typeExample(te.Elem) + "|" + typeExample(te.Elem)
	case KMap:
		return "k:" + typeExample(te.Val) + ";k2:" + typeExample(te.Val)
	}
	return "?"
}

// ------------------------------------------------------------ tables_gen.go

func genTables(tables []*Table, refPK func(string) string, side, note string) string {
	buf := bytes.Buffer{}
	buf.WriteString(genHeader(side, note))
	if len(tables) == 0 {
		return buf.String()
	}
	buf.WriteString("import (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n")
	for _, t := range tables {
		genOneTable(&buf, t, fieldsFor(t, side), refPK)
	}
	return buf.String()
}

func genOneTable(buf *bytes.Buffer, t *Table, fs []*Field, refPK func(string) string) {
	pk := fs[0] // 主键恒为 cs，两端都保留
	pkGo := t.PKGoType()

	fmt.Fprintf(buf, "\n// ================= %s (%s) =================\n\n", t.Sheet, t.File)
	fmt.Fprintf(buf, "// %s 对应 %s[%s] 的一行\n", t.Sheet, t.File, t.Sheet)
	fmt.Fprintf(buf, "type %s struct {\n", t.Sheet)
	for _, f := range fs {
		if f.Comment != "" {
			fmt.Fprintf(buf, "\t// %s\n", f.Comment)
		}
		fmt.Fprintf(buf, "\t%s %s `json:%q`\n", f.GoName, f.Type.GoType(refPK), f.Name)
	}
	buf.WriteString("}\n\n")

	fmt.Fprintf(buf, "// %sTable 是 %s 表的运行时容器，提供主键/索引查询\n", t.Sheet, t.Sheet)
	fmt.Fprintf(buf, "type %sTable struct {\n\trows []*%s\n", t.Sheet, t.Sheet)
	fmt.Fprintf(buf, "\tby%s map[%s]*%s\n", pk.GoName, pkGo, t.Sheet)
	for _, f := range fs[1:] {
		switch {
		case f.Type.Uniq:
			fmt.Fprintf(buf, "\tby%s map[%s]*%s\n", f.GoName, f.Type.GoType(refPK), t.Sheet)
		case f.Type.Index:
			fmt.Fprintf(buf, "\tby%s map[%s][]*%s\n", f.GoName, f.Type.GoType(refPK), t.Sheet)
		}
	}
	buf.WriteString("}\n\n")

	// 构造函数：反序列化 + 建索引 + 兜底校验（防止有人手改 JSON 绕过导表）
	fmt.Fprintf(buf, "func new%sTable(data []byte) (*%sTable, error) {\n", t.Sheet, t.Sheet)
	fmt.Fprintf(buf, "\tvar rows []*%s\n", t.Sheet)
	fmt.Fprintf(buf, "\tif err := json.Unmarshal(data, &rows); err != nil {\n\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n\t}\n", t.Sheet)
	fmt.Fprintf(buf, "\tt := &%sTable{\n\t\trows: rows,\n", t.Sheet)
	fmt.Fprintf(buf, "\t\tby%s: make(map[%s]*%s, len(rows)),\n", pk.GoName, pkGo, t.Sheet)
	for _, f := range fs[1:] {
		switch {
		case f.Type.Uniq:
			fmt.Fprintf(buf, "\t\tby%s: make(map[%s]*%s, len(rows)),\n", f.GoName, f.Type.GoType(refPK), t.Sheet)
		case f.Type.Index:
			fmt.Fprintf(buf, "\t\tby%s: make(map[%s][]*%s, len(rows)),\n", f.GoName, f.Type.GoType(refPK), t.Sheet)
		}
	}
	buf.WriteString("\t}\n\tfor _, r := range rows {\n")
	fmt.Fprintf(buf, "\t\tif _, dup := t.by%s[r.%s]; dup {\n\t\t\treturn nil, fmt.Errorf(\"%s: 主键重复: %%v\", r.%s)\n\t\t}\n\t\tt.by%s[r.%s] = r\n",
		pk.GoName, pk.GoName, t.Sheet, pk.GoName, pk.GoName, pk.GoName)
	for _, f := range fs[1:] {
		switch {
		case f.Type.Uniq:
			fmt.Fprintf(buf, "\t\tif _, dup := t.by%s[r.%s]; dup {\n\t\t\treturn nil, fmt.Errorf(\"%s: 唯一索引 %s 重复: %%v\", r.%s)\n\t\t}\n\t\tt.by%s[r.%s] = r\n",
				f.GoName, f.GoName, t.Sheet, f.GoName, f.GoName, f.GoName, f.GoName)
		case f.Type.Index:
			fmt.Fprintf(buf, "\t\tt.by%s[r.%s] = append(t.by%s[r.%s], r)\n",
				f.GoName, f.GoName, f.GoName, f.GoName)
		}
	}
	buf.WriteString("\t}\n\treturn t, nil\n}\n\n")

	// 访问器
	fmt.Fprintf(buf, "// List 返回全部行（只读，请勿修改）\nfunc (t *%sTable) List() []*%s { return t.rows }\n\n", t.Sheet, t.Sheet)
	fmt.Fprintf(buf, "// Count 返回行数\nfunc (t *%sTable) Count() int { return len(t.rows) }\n\n", t.Sheet)
	fmt.Fprintf(buf, "// Get 按主键 %s 查找，找不到返回 nil\nfunc (t *%sTable) Get(%s %s) *%s { return t.by%s[%s] }\n",
		pk.GoName, t.Sheet, lowerFirst(pk.GoName), pkGo, t.Sheet, pk.GoName, lowerFirst(pk.GoName))
	for _, f := range fs[1:] {
		param := lowerFirst(f.GoName)
		gt := f.Type.GoType(refPK)
		switch {
		case f.Type.Uniq:
			fmt.Fprintf(buf, "\n// GetBy%s 按唯一索引 %s 查找，找不到返回 nil\nfunc (t *%sTable) GetBy%s(%s %s) *%s { return t.by%s[%s] }\n",
				f.GoName, f.Name, t.Sheet, f.GoName, param, gt, t.Sheet, f.GoName, param)
		case f.Type.Index:
			fmt.Fprintf(buf, "\n// GetBy%s 按索引 %s 查找，返回全部命中行（可能为空）\nfunc (t *%sTable) GetBy%s(%s %s) []*%s { return t.by%s[%s] }\n",
				f.GoName, f.Name, t.Sheet, f.GoName, param, gt, t.Sheet, f.GoName, param)
		}
	}
	buf.WriteString("\n")
}

// ------------------------------------------------------------ config_gen.go

func genConfig(tables []*Table, side, note string) string {
	buf := bytes.Buffer{}
	buf.WriteString(genHeader(side, note))
	buf.WriteString("import (\n\t\"fmt\"\n\t\"os\"\n\t\"path/filepath\"\n\t\"strings\"\n)\n\n")
	fmt.Fprintf(&buf, "// Config 是 %s 端所有配置表的聚合根。构建后只读。\ntype Config struct {\n", side)
	for _, t := range tables {
		fmt.Fprintf(&buf, "\t%s *%sTable\n", t.Sheet, t.Sheet)
	}
	buf.WriteString("}\n\n")
	if len(tables) == 0 {
		buf.WriteString("// Load 从目录读取配置（当前没有任何表）\nfunc Load(dir string) (*Config, error) {\n\treturn &Config{}, nil\n}\n")
		return buf.String()
	}

	// buildConfig: Load / LoadEmbedded 共用的构建链
	buf.WriteString("// buildConfig 通过 read 逐表读取并构建。任一步失败即返回错误——热更场景下调用方应继续使用旧 Config。\nfunc buildConfig(read func(name string) ([]byte, error)) (*Config, error) {\n\tc := &Config{}\n\tvar data []byte\n\tvar err error\n")
	for _, t := range tables {
		fmt.Fprintf(&buf, "\tif data, err = read(%q); err == nil {\n\t\tc.%s, err = new%sTable(data)\n\t}\n\tif err != nil {\n\t\treturn nil, err\n\t}\n",
			toSnake(t.Sheet)+".json", t.Sheet, t.Sheet)
	}
	buf.WriteString("\treturn c, nil\n}\n\n")

	buf.WriteString(`// Load 从外部目录读取全部 JSON 配置并构建索引。
func Load(dir string) (*Config, error) {
	return buildConfig(func(name string) ([]byte, error) {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil, fmt.Errorf("读取配置 %s 失败: %w", name, err)
		}
		return data, nil
	})
}

// LoadEmbedded 加载编译进二进制的内嵌配置（见 embed_gen.go）。
// 部署形态: 单二进制，无需携带任何外部数据文件。

// LoadAuto 优先从外部覆盖目录加载；dir 不存在或没有 JSON 时回落到内嵌配置。
// 配合 hotreload.Manager 即为「单二进制部署 + 推文件热更」:
// 往 dir 推一套完整 JSON 即切换生效；清空 dir 则回落内嵌版本。
// 注意: 覆盖目录必须是完整的一套表，缺表会导致加载失败（并保留旧配置）。
func LoadAuto(dir string) (*Config, error) {
	if HasExternal(dir) {
		return Load(dir)
	}
	return LoadEmbedded()
}

// HasExternal 报告 dir 下是否存在外部 JSON 配置
func HasExternal(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".json") {
			return true
		}
	}
	return false
}
`)
	return buf.String()
}

// ------------------------------------------------------------ embed_gen.go

func genEmbed(side, note string) string {
	buf := bytes.Buffer{}
	buf.WriteString(genHeader(side, note))
	buf.WriteString(`import (
	"embed"
	"fmt"
)

// 内嵌配置数据: data/*.json 由 gentable 生成并随 go build 编译进二进制
//
//go:embed data/*.json
var embeddedJSON embed.FS

// LoadEmbedded 加载编译进二进制的内嵌配置
func LoadEmbedded() (*Config, error) {
	return buildConfig(func(name string) ([]byte, error) {
		data, err := embeddedJSON.ReadFile("data/" + name)
		if err != nil {
			return nil, fmt.Errorf("读取内嵌配置 %s 失败: %w", name, err)
		}
		return data, nil
	})
}
`)
	return buf.String()
}
