// Code generated by gentable from Excel. DO NOT EDIT.
// client 端产物: 仅包含导出标记为 cs/c 的字段。

package client

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Config 是 client 端所有配置表的聚合根。构建后只读。
type Config struct {
	Item    *ItemTable
	Monster *MonsterTable
}

// buildConfig 通过 read 逐表读取并构建。任一步失败即返回错误——热更场景下调用方应继续使用旧 Config。
func buildConfig(read func(name string) ([]byte, error)) (*Config, error) {
	c := &Config{}
	var data []byte
	var err error
	if data, err = read("item.json"); err == nil {
		c.Item, err = newItemTable(data)
	}
	if err != nil {
		return nil, err
	}
	if data, err = read("monster.json"); err == nil {
		c.Monster, err = newMonsterTable(data)
	}
	if err != nil {
		return nil, err
	}
	return c, nil
}

// Load 从外部目录读取全部 JSON 配置并构建索引。
func Load(dir string) (*Config, error) {
	return buildConfig(func(name string) ([]byte, error) {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil, fmt.Errorf("读取配置 %s 失败: %w", name, err)
		}
		return data, nil
	})
}

// LoadEmbedded 加载编译进二进制的内嵌配置（见 embed_gen.go）。
// 部署形态: 单二进制，无需携带任何外部数据文件。

// LoadAuto 优先从外部覆盖目录加载；dir 不存在或没有 JSON 时回落到内嵌配置。
// 配合 hotreload.Manager 即为「单二进制部署 + 推文件热更」:
// 往 dir 推一套完整 JSON 即切换生效；清空 dir 则回落内嵌版本。
// 注意: 覆盖目录必须是完整的一套表，缺表会导致加载失败（并保留旧配置）。
func LoadAuto(dir string) (*Config, error) {
	if HasExternal(dir) {
		return Load(dir)
	}
	return LoadEmbedded()
}

// HasExternal 报告 dir 下是否存在外部 JSON 配置
func HasExternal(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".json") {
			return true
		}
	}
	return false
}
