// Code generated by gentable from Excel. DO NOT EDIT.
// client 端产物: 仅包含导出标记为 cs/c 的字段。

package client

import (
	"embed"
	"fmt"
)

// 内嵌配置数据: data/*.json 由 gentable 生成并随 go build 编译进二进制
//
//go:embed data/*.json
var embeddedJSON embed.FS

// LoadEmbedded 加载编译进二进制的内嵌配置
func LoadEmbedded() (*Config, error) {
	return buildConfig(func(name string) ([]byte, bool, error) {
		data, err := embeddedJSON.ReadFile("data/" + name)
		if err != nil {
			return nil, false, fmt.Errorf("读取内嵌配置 %s 失败: %w", name, err)
		}
		return data, false, nil
	})
}
