// Code generated by gentable from Excel. DO NOT EDIT.
// client 端产物: 仅包含导出标记为 cs/c 的字段。

package client

import (
	"encoding/json"
	"fmt"
)

// ================= Item (item.xlsx) =================

// Item 对应 item.xlsx[Item] 的一行
type Item struct {
	// 道具ID(主键)
	Id int32 `json:"id"`
	// 道具名(唯一索引)
	Name string `json:"name"`
	// 品质,见common.xlsx/EnumItemQuality
	Quality ItemQuality `json:"quality"`
	// 售价(铜币)
	Price int32 `json:"price"`
	// 道具描述
	Desc string `json:"desc"`
}

// ItemTable 是 Item 表的运行时容器，提供主键/索引查询
type ItemTable struct {
	rows   []*Item
	byId   map[int32]*Item
	byName map[string]*Item
}

func newItemTable(data []byte) (*ItemTable, error) {
	var rows []*Item
	if err := json.Unmarshal(data, &rows); err != nil {
		return nil, fmt.Errorf("Item: %w", err)
	}
	t := &ItemTable{
		rows:   rows,
		byId:   make(map[int32]*Item, len(rows)),
		byName: make(map[string]*Item, len(rows)),
	}
	for _, r := range rows {
		if _, dup := t.byId[r.Id]; dup {
			return nil, fmt.Errorf("Item: 主键重复: %v", r.Id)
		}
		t.byId[r.Id] = r
		if _, dup := t.byName[r.Name]; dup {
			return nil, fmt.Errorf("Item: 唯一索引 Name 重复: %v", r.Name)
		}
		t.byName[r.Name] = r
	}
	return t, nil
}

// List 返回全部行（只读，请勿修改）
func (t *ItemTable) List() []*Item { return t.rows }

// Count 返回行数
func (t *ItemTable) Count() int { return len(t.rows) }

// Get 按主键 Id 查找，找不到返回 nil
func (t *ItemTable) Get(id int32) *Item { return t.byId[id] }

// GetByName 按唯一索引 name 查找，找不到返回 nil
func (t *ItemTable) GetByName(name string) *Item { return t.byName[name] }

// ================= Monster (monster.xlsx) =================

// Monster 对应 monster.xlsx[Monster] 的一行
type Monster struct {
	// 怪物ID(主键)
	Id int32 `json:"id"`
	// 怪物名(普通索引,可重名)
	Name string `json:"name"`
	// 等级
	Level int32 `json:"level"`
	// 生命值
	Hp int32 `json:"hp"`
	// 标签,用|分隔
	Tags []string `json:"tags"`
	// 出生坐标,如 x:100;y:200
	BornPos Pos `json:"born_pos"`
	// 描述
	Desc string `json:"desc"`
}

// MonsterTable 是 Monster 表的运行时容器，提供主键/索引查询
type MonsterTable struct {
	rows   []*Monster
	byId   map[int32]*Monster
	byName map[string][]*Monster
}

func newMonsterTable(data []byte) (*MonsterTable, error) {
	var rows []*Monster
	if err := json.Unmarshal(data, &rows); err != nil {
		return nil, fmt.Errorf("Monster: %w", err)
	}
	t := &MonsterTable{
		rows:   rows,
		byId:   make(map[int32]*Monster, len(rows)),
		byName: make(map[string][]*Monster, len(rows)),
	}
	for _, r := range rows {
		if _, dup := t.byId[r.Id]; dup {
			return nil, fmt.Errorf("Monster: 主键重复: %v", r.Id)
		}
		t.byId[r.Id] = r
		t.byName[r.Name] = append(t.byName[r.Name], r)
	}
	return t, nil
}

// List 返回全部行（只读，请勿修改）
func (t *MonsterTable) List() []*Monster { return t.rows }

// Count 返回行数
func (t *MonsterTable) Count() int { return len(t.rows) }

// Get 按主键 Id 查找，找不到返回 nil
func (t *MonsterTable) Get(id int32) *Monster { return t.byId[id] }

// GetByName 按索引 name 查找，返回全部命中行（可能为空）
func (t *MonsterTable) GetByName(name string) []*Monster { return t.byName[name] }
